[[pagination]]
= REST Design - Pagination

[#160]
== {SHOULD} support pagination
Access to lists of data items should support pagination to protect the service against overload as well as to
support client side iteration and batch processing experience. This holds true for all lists that are (potentially) larger than just a few hundred entries.

There are two well known page iteration techniques:

* *Offset-based pagination*: numeric offset identifies the first page-entry

* *Cursor-based pagination* — aka key-based pagination: a unique key identifies the first page-entry

**Note:** To provide a consistent look and feel of pagination patterns, you must stick to the common query parameter names defined <<137>>.

== {SHOULD} use Offset-based pagination
Both ways of pagination have their benefits. But the traits which elevate Cursor-based pagination, like high-data volumes or storage in NoSQL databases is not applicable to our current setup.
Offset-based pagination is easier to implement and maintain. Other reasons to chose Offset-based pagination:

* Small data sets of only a few hundred entries.
* we have pages shown in UI
* current datasets are not likely to change very frequent
* Framework support, our chosen tech stack provides easy to use support for Offset-based pagination
* SQL is well-supported by Offset-based pagination

== {MAY} use Cursor-based pagination
Cursor-based pagination has its upsides, and might be better than Offset-based pagination if:

* The dataset is large entries and often changing or added upon
* Data is stored in NoSQL database
* Support for infinite scroll is required
* amount of sorting option is minimal and no multi-sort is required
* jumping to a specific page is not needed