name: Build AsciiDoc

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build AsciiDoc
        run: docker run --interactive --volume=${{ github.workspace }}:/documents/ asciidoctor/docker-asciidoctor:latest asciidoctor -D /documents/output index.adoc
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: html-output
          path: output/